// Generated by CoffeeScript 2.6.1
  // StoryMapper.coffee
import {
  Mapper
} from '@jdeighan/mapper';

// ---------------------------------------------------------------------------
// A Mapper useful for stories
export var StoryMapper = class StoryMapper extends Mapper {
  mapLine(line, level) {
    var _, ident, lMatches, str;
    if (lMatches = line.match(/([A-Za-z_][A-Za-z0-9_]*)\:\s*(.+)$/)) { // identifier
      // colon
      // optional whitespace
      // a non-empty string
      [_, ident, str] = lMatches;
      if (str.match(/\d+(?:\.\d*)?$/)) {
        return line;
      } else {
        // --- surround with single quotes, double internal single quotes
        str = "'" + str.replace(/\'/g, "''") + "'";
        return `${ident}: ${str}`;
      }
    } else {
      return line;
    }
  }

};
