// Generated by CoffeeScript 2.6.1
// Translator.coffee
var combine;

import {
  undef,
  assert,
  isEmpty,
  nonEmpty,
  OL,
  croak
} from '@jdeighan/coffee-utils';

import {
  LOG
} from '@jdeighan/coffee-utils/log';

import {
  debug
} from '@jdeighan/coffee-utils/debug';

import {
  slurpTAML
} from '@jdeighan/mapper/taml';

// ---------------------------------------------------------------------------
export var Translator = class Translator {
  constructor(dictPath = undef) {
    debug("enter Translator()");
    this.hDict = {};
    if (dictPath) {
      this.load(dictPath);
    }
    this.lFound = undef;
    debug("return from Translator()", this.hDict);
  }

  // ..........................................................
  translate(word) {
    return this.hDict[word.toLowerCase()];
  }

  // ..........................................................
  found(str, trans, pos, end) {
    this.lFound.push([str, trans, pos, end]);
  }

  // ..........................................................
  findWords(sent, lPhrases = []) {
    var end, func, h, i, lFound, lcSent, len1, newString, phrase, start;
    // --- lPhrases should have list of {en, zh, pinyin}
    // --- returns [ [<word>, <trans>, <startPos>, <endPos>], .. ]
    debug("enter findWords()", sent);
    if (nonEmpty(lPhrases)) {
      debug("lPhrases", lPhrases);
    }
    this.lFound = [];
    lcSent = sent.toLowerCase();
    for (i = 0, len1 = lPhrases.length; i < len1; i++) {
      h = lPhrases[i];
      phrase = h.en.toLowerCase();
      start = lcSent.indexOf(phrase);
      if (start === -1) {
        LOG("   Phrase not found");
        LOG(`      ${h.en}`);
        LOG(`      ${sent}`);
      } else {
        end = start + phrase.length;
        this.found(phrase, `${h.zh} ${h.pinyin}`, start, end);
      }
    }
    // --- We need to use a "fat arrow" function here
    //     to prevent 'this' being replaced
    func = (match, start) => {
      var trans;
      end = start + match.length;
      if (trans = this.translate(match)) {
        if (!this.hasOverlap(start, end)) {
          this.found(match, trans, start, end);
        }
      }
      return match;
    };
    // --- This will find all matches - it doesn't actually replace
    newString = sent.replace(/\w+/g, func);
    lFound = this.lFound;
    this.lFound = undef;
    debug("return from findWords()", lFound);
    return lFound;
  }

  // ..........................................................
  hasOverlap(start, end) {
    var _, i, lInfo, len1, pEnd, pStart, ref;
    assert(start <= end, "hasOverlap(): Bad positions");
    ref = this.lFound;
    for (i = 0, len1 = ref.length; i < len1; i++) {
      lInfo = ref[i];
      [_, _, pStart, pEnd] = lInfo;
      assert(pStart <= pEnd, "hasOverlap(): Bad phrase positions");
      if ((start <= pEnd) && (end >= pStart)) {
        return true;
      }
    }
    return false;
  }

  // ..........................................................
  load(dictPath) {
    var i, key, lWords, len1, nKeys, ref, trans, word;
    debug(`enter load('${dictPath}')`);
    ref = slurpTAML(dictPath);
    for (key in ref) {
      trans = ref[key];
      lWords = splitKey(key);
      if (lWords === undef) {
        croak(`Bad key: ${OL(key)}`);
      }
      debug("lWords", lWords);
      for (i = 0, len1 = lWords.length; i < len1; i++) {
        word = lWords[i];
        if (this.hDict[word] === undef) {
          this.hDict[word] = trans;
        }
      }
    }
    nKeys = Object.keys(this.hDict).length;
    debug(`return ${nKeys} keys from load()`);
  }

};

// ---------------------------------------------------------------------------
export var splitKey = function(key) {
  var _, base, baselen, dashes, ext, lMatches, lWords, part, ref, strExtensions, toDel, word;
  // --- returns [<word>,...] or undef
  debug(`enter splitKey(${OL(key)})`);
  if (lMatches = key.match(/^([^\(\/]+)((?:\(-*[\'a-z]*\))*)(\/[a-z]+)?$/)) { // normally one of n, v, adj, adv, prep, art
    [_, base, strExtensions, part] = lMatches;
    debug('base', base);
    debug('strExtensions', strExtensions);
    debug('part', part);
    if (nonEmpty(part)) {
      lWords = [base, base + part];
    } else {
      lWords = [base];
    }
    baselen = base.length;
    if (nonEmpty(strExtensions)) {
      ref = strExtensions.matchAll(/\((-*)([\'a-z]*)\)/g);
      for (lMatches of ref) {
        [_, dashes, ext] = lMatches;
        toDel = dashes.length;
        word = base.substring(0, baselen - toDel) + ext;
        lWords.push(word);
        if (nonEmpty(part)) {
          lWords.push(word + part);
        }
      }
    }
    debug("return from splitKey()", lWords);
    return lWords;
  } else {
    debug("return undef from splitKey() - no match");
    return undef;
  }
};

// ---------------------------------------------------------------------------
combine = function(word, ext) {
  var len;
  if (ext.indexOf('--') === 0) {
    len = word.length;
    return word.substring(0, len - 2) + ext.substring(2);
  } else if (ext.indexOf('-') === 0) {
    len = word.length;
    return word.substring(0, len - 1) + ext.substring(1);
  }
  return word + ext;
};
